```{r include=FALSE}

if (!requireNamespace("reticulate", quietly = TRUE)) {
  install.packages("reticulate")
}

# Create list with required libraries
libraries <- c("dplyr", "readr", "reticulate", "ggplot2", "Metrics", "tidyverse", "glmnet", "e1071", "lubridate")


# Loop through each library and check if it's installed, if not, install it and then load it to include in this project
for (lib in libraries)
{
  if (!require(lib, character.only = TRUE))
  {
    install.packages(lib)
    library(lib, character.only = TRUE)
  }
}

# Install the reticulate package if you haven't already
#if (!requireNamespace("reticulate", quietly = TRUE)) {
#  install.packages("reticulate")
#}

# Custom function to check if a Conda environment exists
#condaenv_exists <- function(env_name) {
#  conda_envs <- conda_list()
#  return(env_name %in% conda_envs$name)
#}

# Check if conda is installed, if not, install miniconda
#conda_envs <- conda_list()
#if (length(conda_envs) == 0) {
#  install_miniconda()
#}

# Create a specific Python environment if it doesn't exist
#if (!condaenv_exists("r-reticulate")) {
#  conda_create("r-reticulate", python_version = "3.8")
#}

# Get the list of installed packages in the created environment
# conda_envs <- conda_list()
# r_reticulate_env <- conda_envs[conda_envs$name == "r-reticulate", ]
# installed_packages <- r_reticulate_env$packages

# Install required packages in the created environment
# required_packages <- c("pandas", "numpy", "tensorflow", "h5py")
#
# for (pkg in required_packages) {
#   if (!(pkg %in% installed_packages)) {
#     conda_install("r-reticulate", pkg)
#   }
# }

# If this doesn't install 'tensorflow', go ahead and download anaconda from "https://www.anaconda.com/", open it up, go to environment and choose "r-reticulate". Then install the packages " "pandas", "numpy", "tensorflow", "h5py" " from the UI.
# Error associated with this fix:
# 'InvalidArchiveError("Error with archive C:\\Users\\ [...] \\\compose_set_interface.h.inc'")'
```

```{r}
df <- read_csv("../data/data_clean.csv", show_col_types = FALSE)
```


## Prediction Models (LR, SVM, NN)

Teilen des Datensatzes in Trainings- Validierungs- und Testdatensatz. Diese werden für LR und SVM verwendet.

```{r include=FALSE}
train_data <- subset(df, Datum >= "2013-07-01" & Datum <= "2018-07-30")
validation_data <- subset(df, Datum >= "2018-07-31" & Datum <= "2019-06-08")
test_data <- subset(df, Datum >= "2019-06-09" & Datum <= "2019-07-30")

# Check the dimensions of the datasets
cat("Training dataset dimensions:", dim(train_data), "\n")
cat("Validation dataset dimensions:", dim(validation_data), "\n")
cat("Test dataset dimensions:", dim(test_data), "\n")

```

### LR Beispiel einer einfachen linearen Regression

```{r include=FALSE}
  mod_lr <- lm(Umsatz ~ Datum, df)
    summary(mod_lr)
    
  mod_lr_1 <- lm(Umsatz ~ Datum + as.factor(Warengruppe), df)
    summary(mod_lr_1)
    
  mod_lr_2 <- lm(Umsatz ~ Datum + as.factor(Warengruppe) + as.factor(Wochentag), df)
    summary(mod_lr_2)
    
  mod_lr_3 <- lm(Umsatz ~ Datum + as.factor(Warengruppe) + as.factor(Wochentag) + as.factor(FerienSH), df)
    summary(mod_lr_3)
    
  mod_lr_4 <- lm(Umsatz ~ Datum + as.factor(Warengruppe) + as.factor(Wochentag) + as.factor(FerienSH) + Temperatur, df)
    summary(mod_lr_4)
  
  mod_lr_5 <- lm(Umsatz ~ Datum + as.factor(Warengruppe) + as.factor(Wochentag) + as.factor(FerienSH) + Temperatur + as.factor(KielerWoche), df)
    summary(mod_lr_5)
  
  mod_lr_6 <- lm(Umsatz ~ Datum + as.factor(Warengruppe) + as.factor(Wochentag) + as.factor(FerienSH) + Temperatur + as.factor(KielerWoche) + Bewoelkung, df)
    summary(mod_lr_6)
    
    # Quick comment: KiWo and Bewoelkung do not increase R-squared
    mod_lr_7 <- lm(Umsatz ~ Datum + as.factor(Warengruppe) + as.factor(Wochentag) + as.factor(FerienSH) + Temperatur + as.factor(KielerWoche) + Bewoelkung + Windgeschwindigkeit, df)
    summary(mod_lr_7)
  
    # Windgeschwindigkeit only inproves R-squared marginally.
  mod_lr_8 <- lm(Umsatz ~ Datum + as.factor(Warengruppe) + as.factor(Wochentag) + as.factor(FerienSH) + Temperatur + as.factor(KielerWoche) + Bewoelkung + Windgeschwindigkeit, df)
    summary(mod_lr_8)

mod_lr_9 <- lm(Umsatz ~ Datum * Temperatur + as.factor(Warengruppe) + as.factor(Wochentag) + as.factor(FerienSH) + Temperatur + as.factor(KielerWoche) + Bewoelkung + Windgeschwindigkeit, df)
    summary(mod_lr_9)
    
mod_lr_10 <- lm(Umsatz ~ Datum * Temperatur + as.factor(Warengruppe) + as.factor(Wochentag) + as.factor(FerienSH) + Temperatur + as.factor(KielerWoche) + Bewoelkung + Windgeschwindigkeit, df)
    summary(mod_lr_10)
    
mod_lr_11 <- lm(Umsatz ~ Datum * Temperatur + as.factor(Warengruppe) + as.factor(Wochentag) + as.factor(FerienSH) + Temperatur + as.factor(KielerWoche) + Bewoelkung + Windgeschwindigkeit + as.factor(Monat), df)
    summary(mod_lr_11)
    
mod_lr_12 <- lm(Umsatz ~ Datum + Datum * Temperatur + as.factor(Warengruppe) + as.factor(Wochentag) + as.factor(FerienSH) + Temperatur + as.factor(KielerWoche) + Bewoelkung + Windgeschwindigkeit +  as.factor(Monat) + as.factor(Monat) * Temperatur, df)
    summary(mod_lr_12)
    


```

#### Nutzung des resultierenden Modells für eine Vohersage

```{r include=FALSE}
# Make predictions using the test data
prediction_temp <- read.csv("../data/prediction_template.csv") 

prediction_temp$predicted <- predict(mod_lr_12, newdata = test_data)

prediction_temp <- select(prediction_temp, -Umsatz)

prediction_temp <- prediction_temp %>%
  rename(Umsatz = predicted)


# Compare the predicted values with the actual values
# comparison <- data.frame(Actual = validation_data$Umsatz, Predicted = predicted_values)

# Display the comparison and RMSE
# head(comparison)
# cat("Mean Absolute Percentage Error (MAPE):", mape(comparison$Actual, comparison$Predicted), "\n")




```

```{r}
library(httr)
predictions <- prediction_temp

name <- "Gruppe 11"

# Execution of the request
r <- POST("https://bakery-sales-mape-tolicqztoq-ey.a.run.app/", 
          body = list(name=name, predictions=predictions),
          encode = "json")
# Output of MAPE in Percent
content(r, "parsed", "application/json")
```

