
```{r include=FALSE}
# Create list with required libraries
libraries <- c("dplyr", "readr", "reticulate", "ggplot2", "Metrics", "tidyverse", "glmnet", "e1071", "lubridate", "keras")


# Loop through each library and check if it's installed, if not, install it and then load it to include in this project
for (lib in libraries)
{
  if (!require(lib, character.only = TRUE))
  {
    install.packages(lib)
    library(lib, character.only = TRUE)
  }
}

# Install the reticulate package if you haven't already
if (!requireNamespace("reticulate", quietly = TRUE)) {
  install.packages("reticulate")
}

# Custom function to check if a Conda environment exists
condaenv_exists <- function(env_name) {
  conda_envs <- conda_list()
  return(env_name %in% conda_envs$name)
}

# Check if conda is installed, if not, install miniconda
conda_envs <- conda_list()
if (length(conda_envs) == 0) {
  install_miniconda()
}

# Create a specific Python environment if it doesn't exist
if (!condaenv_exists("r-reticulate")) {
  conda_create("r-reticulate", python_version = "3.8")
}

```



```{python}
model = load_model("../ML_models/mod_nn_18.h5")


```



```{r}
# library(dplyr)
# library(readr)
# library(httr)
# 
# # Dataframe for request must include columns `Datum`, `Warengruppe` und `Umsatz`
# predictions <- read_csv("prediction_template.csv")
# 
# # name must not be provided; however, each team must upload at least one not
# # anonymous prediction
# name <- "Gruppe X"
# 
# # Execution of the request
# r <- POST("https://bakery-sales-mape-tolicqztoq-ey.a.run.app/", 
#           body = list(name=name, predictions=predictions),
#           encode = "json")
# # Output of MAPE in Percent
# content(r, "parsed", "application/json")

```

